### ISSUE TITLE
Architecture Diagram

### ISSUE THREAD

**Issue by jabbarsuku** [dunbarcyber/cyphondock#46]
Can someone share the detailed architecture component diagram of Cuphon

**Comment by lhadjchikh** [comment]
You can view entity relationship (ER) diagrams [here](http://cyphon.readthedocs.io/en/latest/graphs/graphs.html). You can click on some of the "Related Graphs" to explore relationships between models.

We don't have a single graph of all models, since they are so many components that it's pretty overwhelming. However, you could generate one by following [these instructions](http://cyphon.readthedocs.io/en/latest/dev-guide/graphing-models.html).

**Comment by suchandbabu** [comment]
Hi, 
I have installed and using Cyphondock.  Can i create this entity relationship diagram in Cyphondock.
I just installed pyparsing==1.5.7 and pydot,  but it was an unsuccessful attempt to generate the graph using the steps that mentioned in above links. So i doubt whether this will work with cyphondock or not.
