### ISSUE TITLE
Dedicated Logstash instance to Logstash in Cyphondock

### ISSUE THREAD

**Issue by suchandbabu** [dunbarcyber/cyphondock#50]
Hi,
I am trying to forward logs from my dedicated logstash to cyphondock logstash. My dedicated logstash successfully started pipeline to forward logs. Now where can i view this logs , i couldn't find this in kibana or RabbitMQ in cyphondock. please let me know if i need to do any other configuration changes. 
Port is open in Cyphondocke instance.

Dedicated logstash instance: output.conf
output {
    tcp
    {
        host => "xxx.xxx.xxx.xxx"
        port => 1234
    }
}
Cyphondock Logstash Configuration
input {
    tcp
    {
        port => 1234
    }
}

**Comment by suchandbabu** [comment]
**Docker-compose logs -f logstash**

logstash_1       | [2017-11-12T00:48:52,064][INFO ][org.logstash.beats.BeatsHandler] Exception: org.logstash.beats.BeatsParser$InvalidFrameProtocolException: Invalid Frame Type, received: 1, from: /94.207.134.238:48737
logstash_1       | Error grabbing logs: invalid character 'l' after object key:value pair

**Comment by suchandbabu** [comment]
I have installed TCP output plugin only in dedicated logstash instance, please let me know if I need to install same plugin on cyphondock logstash, also please help me to with the command to install logstash plugin in Docker-compose.

**Comment by lhadjchikh** [comment]
Hi @suchandbabu, I would recommend looking to [Logstash](https://www.elastic.co/guide/en/logstash/5.6/index.html) and [Docker Compose](https://docs.docker.com/compose/) documentation/support to figure this out. Cyphondock is really just a set of example configurations for Docker Compose to get a Cyphon stack up and running quickly, but unfortunately we aren't able to provide support for every technology in the stack. If you have issues getting data into RabbitMQ, Logstash, or Elasticsearch, you'll be better off looking to help from those projects (or Docker Compose), since they will be much better able to troubleshoot your problems. However, if you run into problems using the [Cyphon image](https://hub.docker.com/r/dunbar/cyphon/) itself, or in running the Cyphondock configs out-of-the-box, please let us know!
