### ISSUE TITLE
Cyphon Integration Issues 

### ISSUE THREAD

**Issue by jabbarsuku** [dunbarcyber/cyphondock#53]
We are planning to use Cyphon in production environment starting next week, currently we are facing some challenges in integrating Cyphon with the dedicated Logstash Instance , do you offer professional services support for integration issues, if not we would like to develop an internal team for this, we need some suggestions on the skill sets we need to look for?

**Comment by censey** [comment]
@jabbarsuku Thank you for your question.  Are you sure that you need support for Cyphon or Docker / Elastic / Logstash?  Many of the issues that have been opened seem to be around these 3rd party technologies that Cyphon tends to integrate with.  We do not have the ability to support Elastic or Docker directly.  I do realize that (at times) there is a blurry line between the various tools in play here.

**Comment by jabbarsuku** [comment]
The real issue is with forwarding of logs from dedicated log stash instance to Cyphondock, if there is a provision for professional services support we would like to make use of it. If not kindly help us with list of skills we need to look for in candidates.

**Comment by lhadjchikh** [comment]
Sorry you're having difficulties @jabbarsuku. To clarify, Cyphon doesn’t actually communicate with Logstash; it only talks to RabbitMQ and Elasticsearch. If you’re having trouble integrating with an external Logstash instance, the problem probably lies between Logstash and RabbitMQ, or between Logstash and Elasticsearch.

If either RabbitMQ or Elasticsearch is running as a Docker container, you just need to configure the Docker container and your dedicated Logstash instance to talk to each other. This would be done through your Logstash output and your Docker Compose files. You can find docs for Logstash’s RabbitMQ output plugin [here](https://www.elastic.co/guide/en/logstash/current/plugins-outputs-rabbitmq.html). On the Docker end of things, you can make any changes you need to in the Docker Compose files contained in Cyphondock. For example, you may need to map the port of your RabbitMQ container to the host, so that it can talk to an external Logstash instance. You can find docs on the Docker Compose  `ports` setting [here](https://docs.docker.com/compose/compose-file/#ports). 

Once RabbitMQ and Logstash are talking, Cyphon should be able to retrieve documents from RabbitMQ, if you’re using the default settings. If you need to make any changes to Cyphon’s RabbitMQ settings, you can find them in [config/env/cyphon.env](https://github.com/dunbarcyber/cyphondock/blob/master/config-COPYME/env/cyphon.env#L19-L22) or [config/cyphon/settings/conf.py](https://github.com/dunbarcyber/cyphondock/blob/master/config-COPYME/cyphon/settings/conf.py#L208-L215).

With respect to the skills needed for this kind of integration, I'd look for candidates with knowledge of Docker, Docker Compose, Logstash, Elasticsearch, and RabbitMQ. We have a small development team, so unfortunately we only have the ability to support issues specifically related to the [Cyphon](github.com/dunbarcyber/cyphon) or [Cyclops](github.com/dunbarcyber/cyclops) codebases. Cyphondock is just a set of Docker Compose files (nothing special), so any customization that needs to be done to them is probably an issue better addressed by Docker and any services you’re running outside of Docker, such as Logstash.

Hope that provides some clarification and guidance on what skills to look for! We've had to do a lot of troubleshooting with Docker and the Elastic Stack ourselves, but fortunately so many people use these projects that we can usually solutions in their documentation and knowledge bases, though it often takes some digging...

I will try to work on an architecture diagram for how the various services in the stack talk to each other, so it's easier for folks to identify the source of issues they run in to during deployment!
