### ISSUE TITLE
Docker Install (via auto install bash script) can't login

### ISSUE THREAD

**Issue by wtarkington** [dunbarcyber/cyphondock#65]
So I look at the env/cyphone.env and it shows me the username / password but it doesn't work.

It tells you ... you can run manage from the "cyphon" directory but that isn't the case as it's not there unless you mean under the container in which case I'm new to docker and so can't figure out which of the many containers is the container I would need to be at in order to create a new super user.

I'm clearly missing something... I doubt very much if this were more common I wouldn't have found a post or reference to it somewhere.

thanks for the help

**Comment by lhadjchikh** [comment]
Sorry, I should make the documentation more clear. Yes, you'd have to create the superuser from inside the Cyphon container. You can access the shell with this command:
```
sudo docker exec -it cyphondock_cyphon_1 /bin/sh
```
From there, you should be able to run `python manage.py` commands.

**Comment by wtarkington** [comment]
More curious as to why the cyphone.env has cred's that aren't working. Is that a bug just to me?

**Comment by lhadjchikh** [comment]
Those credentials only work when you run Cyphondock in dev mode (see note [here](http://cyphon.readthedocs.io/en/latest/getting-started/create-superuser.html)). This is configured through the `CYPHON_SUPERUSER` environment setting in [docker-compose.dev.yml](https://github.com/dunbarcyber/cyphondock/blob/master/docker-compose.dev.yml#L25), and invoked in the [entrypoints/run.sh](https://github.com/dunbarcyber/cyphon/blob/master/entrypoints/run.sh#L30-#L37) script. I didn't want to enable default credentials in production mode due to security concerns, as I was afraid some people might not remember to change their superuser credentials. I will try to make that clearer in the documentation, though!

**Comment by wtarkington** [comment]
Aha that makes perfect sense thanks so much.... now I'm digging in.
